version: "3.9" # อัปเดตเป็นเวอร์ชันล่าสุดที่มีความเสถียร
services:
  # ส่วนของ PHP และ Apache
  web:
    container_name: php-apache
    build:
      context: ./php
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - ./php/src:/var/www/html
    ports:
      - "8080:80"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # ส่วนของ MySQL
  db:
    container_name: mysql
    image: mysql:8.4 # อัปเดตเป็นเวอร์ชันล่าสุด
    restart: unless-stopped
    ports:
      - "9906:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD:-1234}"
      MYSQL_DATABASE: "${MYSQL_DATABASE:-sales_db}"
      MYSQL_USER: "${MYSQL_USER:-user}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD:-userpassword}"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 20s
      timeout: 5s
      retries: 5

  # ส่วนของ phpMyAdmin
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin:latest
    restart: unless-stopped
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD:-1234}"
    depends_on:
      - db
    networks:
      - app-network

# กำหนด volumes เหมาะกับ Production
# volumes:
#   mysql-data:

# กำหนด network
networks:
  app-network:
    driver: bridge
